server:
  port: 9000
  servlet:
    context-path: /auth

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/an_user_client_management
    username: authorizationDB
    password: connectAuthDB
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    web: TRACE